In [111]:
import numpy as np
from scipy.linalg import lu
from scipy import linalg
from scipy.special import jacobi
import scipy

### Solve the following system of equations using LU Decomposition method:
#### Find L and U by hand.
#### Confirm that A=LU then solve.
- Ex1. 𝟐𝒙+𝟓𝒚=𝟐𝟏, 𝒙+𝟐𝒚=𝟖.
- Ex2. 𝒙𝟏+𝒙𝟐+𝒙𝟑=𝟏, 𝟒𝒙𝟏+𝟑𝒙𝟐−𝒙𝟑=𝟔, 𝟑𝒙𝟏+𝟓𝒙_𝟐+𝟑𝒙𝟑=𝟒

#### Use scipy.linalg.lu() to slove the previous system using LU decomposition and compare the results.

### Note (when using scipy):
- In the second system of equations We can see the <b>L and U</b> we get are different from the ones we got by hand. 
- You will also see there is a permutation matrix <b>P</b> that returned by the <b>lu function</b>. 
- This permutation matrix record how do we change the order of the equations for easier calculation purposes (for example, if first element in first row is zero, it can not be the pivot equation, since you can not turn the first elements in other rows to zero. Therefore, we need to switch the order of the equations to get a new pivot equation). 
- If you multiply <b>P with A</b>, you will see that this permutation matrix effect.
- You will need to arrange the ouput based on the new matrix <b>A</b> achieved by <b>LU</b> multiplication in order to correctly solve the system of equations.

In [72]:
A = np.array([[2,5],[1,2]])
y=np.array([[21],[8]])
p, l, u = lu(A)
print("this is A\n", A,"\n")
print(" this is L * U\n",l@u)
print("**********************")
print("****** this is M ******")
m=linalg.inv(l)@y
print(m)
print("**********************")
print("***** this is X ******")
x=linalg.inv(u)@m
print(x)

this is A
 [[2 5]
 [1 2]] 

 this is L * U
 [[2. 5.]
 [1. 2.]]
**********************
****** this is M ******
[[21. ]
 [-2.5]]
**********************
***** this is X ******
[[-2.]
 [ 5.]]


In [73]:
def calc(a,y,l,u):
    p, l, u = lu(a)
    print("this is A\n", a,"\n")
    print(" this is L * U\n",l@u)
    print("**********************")
    print("****** this is M ******","\n")
    m=linalg.inv(l)@y
    print(m,"\n")
    print("**********************")
    print("***** this is X ******","\n")
    x=linalg.inv(u)@m
    print(x,"\n")
    return x,m,p,l,u

In [74]:
A = np.array([[2,5],[1,2]])
l=[[1,0],[0.5,1]]
u=[[2,5],[0,-0.5]]
y=np.array([[21],[8]])
x,m,p,l,u=calc(A,y,l,u)

this is A
 [[2 5]
 [1 2]] 

 this is L * U
 [[2. 5.]
 [1. 2.]]
**********************
****** this is M ****** 

[[21. ]
 [-2.5]] 

**********************
***** this is X ****** 

[[-2.]
 [ 5.]] 



In [75]:
A = np.array([[1,1,1],[4,3,-1],[3,5,3]])
L=np.array([[1,0,0],[4,1,0],[3,-2,1]])
U=np.array([[1,1,1],[0,-1,-5],[0,0,-10]])
y=np.array([[1],[6],[4]])

print("this is A\n", A,"\n")
print(" this is L * U\n",L@U)
print("**********************")
print("****** this is M ******")
m=linalg.inv(L)@y
print(m)
print("**********************")
print("***** this is X ******")
x=linalg.inv(U)@m
print(x)

this is A
 [[ 1  1  1]
 [ 4  3 -1]
 [ 3  5  3]] 

 this is L * U
 [[ 1  1  1]
 [ 4  3 -1]
 [ 3  5  3]]
**********************
****** this is M ******
[[1.]
 [2.]
 [5.]]
**********************
***** this is X ******
[[ 1. ]
 [ 0.5]
 [-0.5]]


In [79]:
A = np.array([[1,1,1],[4,3,-1],[3,5,3]])
p, l, u = lu(A)
y=np.array([[1],[6],[4]])
y_new=linalg.inv(p)@y
print("this is A\n", A,"\n")
print(" this is L * U\n",l@u)
print("**********************")
print("****** this is M ******")
m=linalg.inv(l)@y_new
print(m)
print("**********************")
print("***** this is X ******")
x=linalg.inv(u)@m
print(x)

this is A
 [[ 1  1  1]
 [ 4  3 -1]
 [ 3  5  3]] 

 this is L * U
 [[ 4.  3. -1.]
 [ 3.  5.  3.]
 [ 1.  1.  1.]]
**********************
****** this is M ******
[[ 6.        ]
 [-0.5       ]
 [-0.45454545]]
**********************
***** this is X ******
[[ 1. ]
 [ 0.5]
 [-0.5]]


A = [[ 1  1  1]
 [ 4  3 -1]
 [ 3  5  3]]
LU =  [[ 1  1  1]
 [ 4  3 -1]
 [ 3  5  3]]
M = [[1.]
 [2.]
 [5.]]
x = [[ 1. ]
 [ 0.5]
 [-0.5]]


P:
 [[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
L:
 [[1.         0.         0.        ]
 [0.75       1.         0.        ]
 [0.25       0.09090909 1.        ]]
U:
 [[ 4.          3.         -1.        ]
 [ 0.          2.75        3.75      ]
 [ 0.          0.          0.90909091]]
LU:
 [[ 4.  3. -1.]
 [ 3.  5.  3.]
 [ 1.  1.  1.]]
A:
 [[ 1  1  1]
 [ 4  3 -1]
 [ 3  5  3]]


M = [[ 6.        ]
 [-0.5       ]
 [-0.45454545]]
x = [[ 1. ]
 [ 0.5]
 [-0.5]]


### Apply the Jacobi and Gauss-Seidel method to solve
- 𝟓𝒙𝟏−𝟐𝒙𝟐+𝟑𝒙𝟑=−𝟏, −𝟑𝒙𝟏+𝟗𝒙𝟐+𝒙𝟑=𝟐, 𝟐𝒙𝟏−𝒙𝟐−𝟕𝒙𝟑=𝟑
- Solve once without vectorization then use vectorize implementation.
- Check for convergance.
- Use different tolerence and see the difference between the two methods. e.g. tol: 0.01,0.001,0.0001 ... etc.

In [107]:
## Jacobi Not Vectorized
epsilon = 0.00001
x1=-1
x2=2
x3=3
t=1
while t:
    x1_old=x1
    x2_old=x2
    x3_old=x3
    x1=(2*x2-3*x3-1)/5
    x2=(3*x1-x3+2)/9
    x3=(-2*x1+x2+3)/-7
    print(x1,x2,x3)
    if np.abs(x1-x1_old) < epsilon and np.abs(x2-x2_old) < epsilon and np.abs(x3-x3_old) < epsilon:
        t = 0

-1.2 -0.5111111111111111 -0.6984126984126985
0.01460317460317464 0.3046913580246914 -0.46792642983119176
0.2026324011085916 0.3417581814618852 -0.4194990541778146
0.18840270509144283 0.331634129939127 -0.4221183885366059
0.18592468509761434 0.3310991604254943 -0.42274997003289505
0.18608964618993476 0.3312243231780777 -0.4227207186854583
0.18612216048250607 0.3312319111258863 -0.42271251288012485
0.1861202721784294 0.3312303699350459 -0.4227128322254553


In [109]:
## Gauss-Seidel Not Vectorized
epsilon = 0.00001
epsilon = 0.00001
x1=-1
x2=2
x3=3
t=1
while t:
    x1_old=x1
    x2_old=x2
    x3_old=x3
    x1=(2*x2_old-3*x3_old-1)/5
    x2=(3*x1-x3_old+2)/9
    x3=(-2*x1+x2_old+3)/-7
    print(x1,x2,x3)
    if np.abs(x1-x1_old) < epsilon and np.abs(x2-x2_old) < epsilon and np.abs(x3-x3_old) < epsilon:
        t = 0

-1.2 -0.5111111111111111 -1.0571428571428572
0.2298412698412699 0.41629629629629633 -0.2898866213151927
0.14045049130763418 0.30124867724867727 -0.4479136162401468
0.18924764064355903 0.3350729486856471 -0.4175361994230799
0.18455089912810677 0.33013209964526674 -0.42371016434706193
0.18627893846634383 0.33139410886067705 -0.42251060324465417
0.18606400549106333 0.3311891799686493 -0.4227522996969358
0.18612705180562122 0.3312370505681999 -0.422705010908201
0.1861178267722005 0.33122872124720026 -0.42271448528911415


In [112]:
## Jacobi Vectorized
epsilon = 0.00001
d=np.diag(np.diag(A))
u=np.triu(A,k=1)
l=np.tril(A,k=-1)
x=np.array([[0],[0],[0]])
T=scipy.linalg.inv(d)@(-l-u)
c=scipy.linalg.inv(d)@y
t=1
while t:
    x_old=x
    x=T@x+c
    if np.abs(x-x_old).max() < epsilon:
        t=0
    print(x)

[[ 0.2       ]
 [ 0.22222222]
 [-0.42857143]]
[[ 0.54603175]
 [ 0.33650794]
 [-0.4031746 ]]
[[ 0.57650794]
 [ 0.44902998]
 [-0.32063492]]
[[ 0.57199295]
 [ 0.45001764]
 [-0.32800202]]
[[ 0.57680826]
 [ 0.44933121]
 [-0.32943311]]
[[ 0.57739235]
 [ 0.45109532]
 [-0.32795924]]
[[ 0.57721367]
 [ 0.45112625]
 [-0.32804438]]
[[ 0.57727713]
 [ 0.45107615]
 [-0.32809984]]
[[ 0.57729037]
 [ 0.45110347]
 [-0.32807456]]
[[ 0.57728612]
 [ 0.45110507]
 [-0.32807468]]


In [113]:
## Gauss-Seidel Vectorized
epsilon = 0.00001
d = np.diag(np.diag(A))
u = np.triu(A,k=1)
l = np.tril(A,k=-1)
x = np.array([ [0],
               [0],
               [0]])                
T = scipy.linalg.inv(d+l)@(-u)
c = scipy.linalg.inv(d+l)@y
t = True
while t:
    x_old = x
    x = T@x + c
    if np.abs(x-x_old).max() < epsilon:
        t = False
    print(x)

[[ 0.2       ]
 [ 0.28888889]
 [-0.41269841]]
[[ 0.5631746 ]
 [ 0.45580247]
 [-0.33277904]]
[[ 0.58198841]
 [ 0.45319381]
 [-0.327031  ]]
[[ 0.57749612]
 [ 0.45105771]
 [-0.32800935]]
[[ 0.57722869]
 [ 0.45107727]
 [-0.32808855]]
[[ 0.57728404]
 [ 0.45110452]
 [-0.32807663]]
[[ 0.57728779]
 [ 0.45110444]
 [-0.32807555]]


### Use np.linalg.solve() to solve the previous system and compare the results.

array([[ 0.18611987],
       [ 0.33123028],
       [-0.42271293]])

### Use scipy.linalg.lu() to slove the previous system using LU decomposition and compare the results.

In [105]:
P

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [106]:
L

array([[ 1.        ,  0.        ,  0.        ],
       [-0.6       ,  1.        ,  0.        ],
       [ 0.4       , -0.02564103,  1.        ]])

In [107]:
U

array([[ 5.        , -2.        ,  3.        ],
       [ 0.        ,  7.8       ,  2.8       ],
       [ 0.        ,  0.        , -8.12820513]])

A = [[ 5 -2  3]
 [-3  9  1]
 [ 2 -1 -7]]
LU =  [[ 5. -2.  3.]
 [-3.  9.  1.]
 [ 2. -1. -7.]]
M = [[-1.        ]
 [ 1.4       ]
 [ 3.43589744]]

Solution: 
x = [[ 0.1861206 ]
 [ 0.33123065]
 [-0.42271278]]
